In [3]:
import pandas as pd

# Crear un conjunto de datos ficticio
data = {
    'Nombre': ['Juan', 'Ana', 'Pedro', 'Luisa', 'Carlos'],
    'Edad': [28, 34, 23, 45, 33],
    'Ciudad': ['Madrid', 'Barcelona', 'Sevilla', 'Valencia', 'Bilbao']
}

# Crear el DataFrame
df = pd.DataFrame(data)

# 1. Guardar el DataFrame en un archivo CSV (sin index=False)
df.to_csv('data/output/datos.csv')

# 2. Guardar el CSV con un delimitador personalizado (punto y coma)
df.to_csv('data/output/datos_punto_coma.csv', sep=';')

# 3. Guardar solo algunas columnas (por ejemplo, 'Nombre' y 'Edad')
df.to_csv('data/output/datos_nombre_edad.csv', columns=['Nombre', 'Edad'])

# 4. Guardar el CSV con codificaci√≥n UTF-8
df.to_csv('data/output/datos_utf8.csv', encoding='utf-8')

# 5. Guardar en un archivo CSV comprimido (gzip)
df.to_csv('data/output/datos_comprimidos.csv.gz', compression='gzip')

# 6. Guardar en un archivo CSV comprimido (zip)
df.to_csv('data/output/datos_comprimidos.zip', compression='zip')

# 7. Leer el archivo CSV guardado y mostrarlo
df_leido = pd.read_csv('data/output/datos.csv')
df_leido

   Unnamed: 0  Nombre  Edad     Ciudad
0           0    Juan    28     Madrid
1           1     Ana    34  Barcelona
2           2   Pedro    23    Sevilla
3           3   Luisa    45   Valencia
4           4  Carlos    33     Bilbao